### ISSUE TITLE
PHP warning when saving a new maintenance record

### ISSUE THREAD

**Issue by maslme** [nitsan-technologies/nitsan_maintenance#11]
When I try to create a new maintenance record in the TYPO3 BE, I fill out all necessary form fields - and the click the save button I got the following PHP warning. The record isn't stored.
PHP Warning: spl_object_hash() expects parameter 1 to be object, null given in [...]/typo3/sysext/extbase/Classes/Persistence/ObjectStorage.php line 187

typo3 10.4.28
PHP 7.4.29

**Comment by nitsan-technologies** [comment]
Hello @maslme 

Thanks for the finding. FYI, We have resolved this issue and released a new version. Can you please download a new version?

Let's know if you are still facing any issue in this.

Thanks!
Team NITSAN

**Comment by maslme** [comment]
Yes,
it seams to work for me - now under TYPO3 11.5.16 and PHP 8.0.18
