### ISSUE TITLE
Cannot save maintenance mode

### ISSUE THREAD

**Issue by jkkoenig** [nitsan-technologies/nitsan_maintenance#6]
Hello,

I just installed your Plugin on Typo3 8.7.27 and included the template. When I tried to save the configuration settings I get the following message:
```
Oops, an error occurred!
Exception while property mapping at property path "image.0": Property "name" was not found in target object of type "Nitsan\NitsanMaintenance\Domain\Model\FileReference".
More information regarding this error might be available online.
```
What can I do?

**Comment by Hobokens** [comment]
same problem here: https://github.com/nitsan-technologies/nitsan_maintenance/issues/8

Did you find a solution in the meantime?

**Comment by jkkoenig** [comment]
I updated Typo3 to V 9.5.8 and nitsan_maintenance to V 2.0.1. Now I can save, but do not see any maintenance mode page

**Comment by nitsan-technologies** [comment]
Hey @jkkoenig 

Thanks for using this extension.

For TYPO3 8 we will check it in deep.

@jkkoenig for TYPO3 9

Do the following things.
1) If you are login at backend then please logout once save maintenance mode form. Then you will get the results from the same browser.
2) You can check it with a different browser in which you are not logged in at backend.

Let me know if you are still facing difficulties. 

Cheers!

**Comment by Hobokens** [comment]
@jkkoenig strange, I'm using TYPO3 9.5.9 and nitsan_maintenance v2.0.1 and still have the described problem. with the error message above.

@nitsan-technologies I can't save the maintenance mode form because of the error.

**Comment by webdev2027** [comment]
I also can't save the maintenance mode:
`PHP Warning: spl_object_hash() expects parameter 1 to be object, integer given in /web/servers/toptica_dev/dev.toptica.com/docs/typo3_src/typo3_src-8.7.28/typo3/sysext/extbase/Classes/Persistence/ObjectStorage.php line 193`

TYPO3 8.7.28  show or hide .. doesn't matter. I always get this error. Extension in version 4.0.0

**Comment by nitsan-technologies** [comment]
Hey @webdev2027 
Sorry for the inconvenience, 

Facing issues while saving settings are fixed. 
Please check with our new released version


Thanks!
